---
- name: NETCONF create NTP server
  hosts: R1
  connection: local
  gather_facts: False

  tasks:

    - name: set ntp server in the device
      ansible.netcommon.netconf_config:
        content: "{{ lookup('template', 'ntp_netconf.j2') }}"

    - name: configurable backup path
      ansible.netcommon.netconf_config:
        backup: yes
        backup_options:
          filename: backup.cfg
          dir_path: /home/expert